language: node_js
node_js:
    - "10"
cache: npm
env:
  - ENV=TRAVIS
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm run build
  - npm run test
branches:
  only:
  - master

