language: node_js
node_js:
    - "10"
cache: npm
env:
  - ENV=TRAVIS
install:
  - rm -rf node_modules
  - npm install
  - npm run clean
  - npm run update
script:
  - npm run build
  - npm run test:unit
branches:
  only:
  - master

