language: node_js
node_js:
    - "10"
cache: npm
env:
  - ENV=TRAVIS
install:
  - npm install -g lerna
  - rm -rf node_modules
  - npx lerna clean --yes
  - npx lerna bootstrap
script:
  - npm run build
  - npm run test:unit
branches:
  only:
  - master

