name: NPM

on:
  push:
    branches: 
      - master
    paths:
      - '*.ts'
      - '!*test.ts'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-java@v1
      with:
        java-version: '9.X'
        architecture: x64
    - name: npm install
      run: |
        npm install
      env:
        CI: true
    - name: build and test
      run: |
        npm run build
        npm run test
      env:
        CI: true
    - name: publish
      if: github.event_name != 'pull_request'
      run: |
        echo placeholder to publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
