name: Build Validation

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-java@v1
      with:
        java-version: '9.X'
        architecture: x64
    - name: Install
      run: |
        npm install
      env:
        CI: true
    - name: Build
      run: |
        npm run build
    - name: Test
      run: |
        java -jar mock/yggdrasil-mock-server-0.0.1-SNAPSHOT.jar
        npm run test
